services:
  db:
    image: postgres:16
    container_name: pm_postgres
    restart: always
    environment:
      POSTGRES_DB: pm_platform
      POSTGRES_USER: pm_user
      POSTGRES_PASSWORD: pm_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: