# Generated by Django 6.0.6 on 2026-07-03 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='body',
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default='', validators=[django.core.validators.MinLengthValidator(1)]),
            preserve_default=False,
        ),
    ]
